import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors, radius } from '@/theme';
export default function Payment(){const {language,updateStatus}=useApp();const ar=language==='ar';const [paid,setPaid]=useState(false);if(paid)return <View style={s.success}><View style={s.successIcon}><Ionicons name="checkmark" size={42} color="#fff"/></View><Text style={s.successTitle}>{ar?'تم الدفع بنجاح':'Payment successful'}</Text><Text style={s.successText}>{ar?'تم اعتماد الإصلاح. بنخبرج بكل تحديث إلى أن تكون السيارة جاهزة.':'Repair is approved. We’ll notify you at every step until your vehicle is ready.'}</Text><Pressable style={s.cta} onPress={()=>{updateStatus('repairing');router.replace('/(tabs)/jobs')}}><Text style={s.ctaText}>{ar?'متابعة الخدمة':'Track repair progress'}</Text></Pressable></View>;return <View style={s.page}><View style={s.nav}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20}/></Pressable><Text style={s.navTitle}>{ar?'الدفع الآمن':'Secure payment'}</Text><View style={{width:42}}/></View><Card><View style={s.totalRow}><Text style={s.totalLabel}>{ar?'المبلغ المستحق':'Amount due'}</Text><Text style={s.total}>AED 1,260</Text></View><Text style={s.meta}>CF-24819 · Al Quoz Auto Care</Text></Card><Text style={s.section}>{ar?'طريقة الدفع':'Payment method'}</Text><Card><View style={s.method}><View style={s.cardIcon}><Ionicons name="card" size={23} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.methodTitle}>{ar?'بطاقة بنكية':'Credit / debit card'}</Text><Text style={s.meta}>•••• 4821 · Visa</Text></View><Ionicons name="checkmark-circle" size={22} color={colors.primary}/></View></Card><Card><View style={s.method}><View style={s.cardIcon}><Ionicons name="logo-apple" size={23} color={colors.ink}/></View><Text style={s.methodTitle}>Apple Pay</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></View></Card><View style={s.secure}><Ionicons name="lock-closed" size={16} color={colors.primary}/><Text style={s.secureText}>{ar?'واجهة تجريبية — اربطي بوابة دفع UAE قبل الإطلاق.':'Demo checkout UI — connect a UAE payment gateway before launch.'}</Text></View><Pressable style={s.cta} onPress={()=>setPaid(true)}><Ionicons name="lock-closed" size={17} color="#fff"/><Text style={s.ctaText}>{ar?'ادفعي 1,260 درهم':'Pay AED 1,260'}</Text></Pressable></View>}
const s=StyleSheet.create({page:{flex:1,padding:20,paddingTop:54,gap:16,backgroundColor:colors.canvas},nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{width:42,height:42,borderRadius:15,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},navTitle:{fontSize:16,fontWeight:'900',color:colors.ink},totalRow:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},totalLabel:{fontSize:13,color:colors.muted},total:{fontSize:27,fontWeight:'900',color:colors.ink},meta:{fontSize:11,color:colors.muted,marginTop:5},section:{fontSize:16,fontWeight:'900',color:colors.ink,marginTop:4},method:{flexDirection:'row',alignItems:'center',gap:12},cardIcon:{width:45,height:45,borderRadius:15,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center'},methodTitle:{fontSize:14,fontWeight:'900',color:colors.ink,flex:1},secure:{flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:8},secureText:{fontSize:11,color:colors.muted,flex:1,lineHeight:16},cta:{marginTop:'auto',backgroundColor:colors.primary,borderRadius:18,padding:17,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},ctaText:{color:'#fff',fontWeight:'900'},success:{flex:1,backgroundColor:colors.canvas,alignItems:'center',justifyContent:'center',padding:35},successIcon:{width:84,height:84,borderRadius:30,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},successTitle:{fontSize:28,fontWeight:'900',color:colors.ink,marginTop:25},successText:{fontSize:14,lineHeight:22,color:colors.muted,textAlign:'center',marginTop:10,marginBottom:30},}) as Record<string, any>
