import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { processPayment } from '@/services/payment';
import { colors } from '@/theme';
export default function CustomPayment(){const {amount='0'}=useLocalSearchParams<{amount:string}>();const {language,methods,selectedPaymentId,selectPayment,recordPayment,job}=useApp();const ar=language==='ar';const [loading,setLoading]=useState(false);const value=Number(amount)||0;const pay=async()=>{const method=methods.find(m=>m.id===selectedPaymentId)!;setLoading(true);try{const result=await processPayment({jobId:job.id,amount:value,method});recordPayment(result);Alert.alert(ar?'تم الدفع':'Payment successful',`${ar?'المرجع':'Reference'}: ${result.reference}`,[{text:'OK',onPress:()=>router.replace('/(tabs)/jobs')}]);}catch{Alert.alert('Payment failed','Please try again.')}finally{setLoading(false)}};return <ScrollView style={s.bg} contentContainerStyle={s.page}><View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={21}/></Pressable><View><Text style={s.title}>{ar?'الدفع':'Payment'}</Text><Text style={s.sub}>{ar?'اختاري طريقة الدفع':'Choose a payment method'}</Text></View></View>
 <Card style={s.amount}><Pill label={ar?'دفع آمن':'SECURE CHECKOUT'} tone="mint" icon="lock-closed"/><Text style={s.amountLabel}>{ar?'المبلغ المستحق':'Amount due'}</Text><Text style={s.amountValue}>AED {value.toFixed(2)}</Text><Text style={s.amountMeta}>Carma Fix · {job.id}</Text></Card>
 <Text style={s.section}>{ar?'طرق الدفع':'Payment methods'}</Text>{methods.map(m=>{const on=m.id===selectedPaymentId;return <Pressable key={m.id} onPress={()=>selectPayment(m.id)}><Card style={[s.method,on&&s.methodOn]}><View style={[s.methodIcon,on&&s.methodIconOn]}><Ionicons name={m.icon as any} size={22} color={on?'#fff':colors.ink}/></View><View style={{flex:1}}><Text style={s.methodName}>{m.label}</Text><Text style={s.methodDetail}>{m.detail}</Text></View><View style={[s.radio,on&&s.radioOn]}>{on&&<View style={s.radioDot}/>}</View></Card></Pressable>})}
 <View style={s.provider}><Ionicons name="information-circle-outline" size={18} color={colors.blue}/><Text style={s.providerText}>{ar?'نسخة الاختبار تكمل الدفع داخل التطبيق. في الإنتاج يتم ربط بوابة الدفع بحساب التاجر ومفاتيح الخادم.':'Demo mode completes payments locally. Production uses your merchant account and server-created payment intents.'}</Text></View>
 <Pressable style={[s.pay,loading&&{opacity:.7}]} disabled={loading} onPress={pay}>{loading?<ActivityIndicator color="#fff"/>:<><Ionicons name="lock-closed" size={17} color="#fff"/><Text style={s.payText}>{ar?'ادفعي الآن':'Pay now'} · AED {value.toFixed(2)}</Text></>}</Pressable>
 </ScrollView>}
const s=StyleSheet.create({bg:{backgroundColor:colors.canvas},page:{padding:18,paddingTop:58,paddingBottom:40,gap:14},head:{flexDirection:'row',alignItems:'center',gap:12},back:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},title:{fontSize:25,fontWeight:'900',color:colors.ink},sub:{fontSize:10.5,color:colors.muted,marginTop:3},amount:{alignItems:'center',paddingVertical:24},amountLabel:{fontSize:10,color:colors.muted,marginTop:17},amountValue:{fontSize:31,fontWeight:'900',letterSpacing:-1,color:colors.ink,marginTop:4},amountMeta:{fontSize:9.5,color:colors.muted2,marginTop:5},section:{fontSize:17,fontWeight:'900',color:colors.ink,marginTop:4},method:{flexDirection:'row',alignItems:'center',gap:12,padding:14},methodOn:{borderColor:colors.primary,borderWidth:1.5},methodIcon:{width:45,height:45,borderRadius:14,backgroundColor:colors.canvas,alignItems:'center',justifyContent:'center'},methodIconOn:{backgroundColor:colors.primary},methodName:{fontSize:12.5,fontWeight:'900',color:colors.ink},methodDetail:{fontSize:9.5,color:colors.muted,marginTop:3},radio:{width:22,height:22,borderRadius:11,borderWidth:1.5,borderColor:colors.lineStrong,alignItems:'center',justifyContent:'center'},radioOn:{borderColor:colors.primary},radioDot:{width:11,height:11,borderRadius:6,backgroundColor:colors.primary},provider:{backgroundColor:colors.blueSoft,borderRadius:15,padding:13,flexDirection:'row',gap:9,alignItems:'flex-start'},providerText:{fontSize:9.5,color:colors.ink2,lineHeight:15,flex:1},pay:{backgroundColor:colors.primary,borderRadius:17,paddingVertical:16,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},payText:{fontSize:13,fontWeight:'900',color:'#fff'}}) as Record<string, any>
