import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import React,{useRef,useState} from 'react';
import {KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {AmbientBackground,BrandMark,Card,Glass,Pill} from '@/components/UI';
import {useApp} from '@/context/AppContext';
import {askCarmaAI} from '@/services/ai';
import {useTheme} from '@/theme';

type Msg={id:string;role:'user'|'assistant';text:string};
export default function Assistant(){
 const {language,selectedVehicle,job}=useApp();const {theme}=useTheme();const ar=language==='ar';
 const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const scroll=useRef<ScrollView>(null);
 const [messages,setMessages]=useState<Msg[]>([{id:'welcome',role:'assistant',text:ar?'هلا، أنا Carma AI. أقدر أساعدج في فهم مشكلة السيارة، شرح عرض السعر، أو متابعة التصليح. شنو حابة تعرفين؟':'Hi, I’m Carma AI. I can help explain car symptoms, clarify your estimate, or track a repair. What would you like to know?'}]);
 const quick=ar?['السيارة ما تشتغل','اشرح لي عرض السعر','وين وصلت سيارتي؟','هل أقدر أسوق؟']:['My car won’t start','Explain my estimate','Where is my car?','Is it safe to drive?'];
 async function send(text=input){if(!text.trim()||busy)return;const u={id:`u${Date.now()}`,role:'user' as const,text:text.trim()};setMessages(m=>[...m,u]);setInput('');setBusy(true);setTimeout(()=>scroll.current?.scrollToEnd({animated:true}),30);const reply=await askCarmaAI(u.text,{vehicle:selectedVehicle,job,language});setMessages(m=>[...m,{id:`a${Date.now()}`,role:'assistant',text:reply}]);setBusy(false);setTimeout(()=>scroll.current?.scrollToEnd({animated:true}),30)}
 return <KeyboardAvoidingView style={[s.screen,{backgroundColor:theme.canvas}]} behavior={Platform.OS==='ios'?'padding':undefined}><AmbientBackground/><View style={s.header}><Pressable onPress={()=>router.back()} style={[s.circle,{backgroundColor:theme.surfaceElevated,borderColor:theme.line}]}><Ionicons name="chevron-down" size={20} color={theme.ink}/></Pressable><View style={s.headBrand}><BrandMark small/><View><Text style={[s.title,{color:theme.ink}]}>Carma AI</Text><View style={s.online}><View style={[s.dot,{backgroundColor:theme.primary}]}/><Text style={[s.onlineText,{color:theme.muted}]}>{ar?'مساعد ذكي':'Intelligent assistant'}</Text></View></View></View><Pressable style={[s.circle,{backgroundColor:theme.surfaceElevated,borderColor:theme.line}]}><Ionicons name="ellipsis-horizontal" size={20} color={theme.ink}/></Pressable></View>
 <ScrollView ref={scroll} contentContainerStyle={s.chat} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
  <Card style={s.context}><View style={s.contextRow}><View style={[s.vehicleIcon,{backgroundColor:theme.primarySoft}]}><Ionicons name="car-sport" size={18} color={theme.primary}/></View><View style={{flex:1}}><Text style={[s.contextLabel,{color:theme.muted}]}>{ar?'السياق الحالي':'CURRENT CONTEXT'}</Text><Text style={[s.contextValue,{color:theme.ink}]}>{selectedVehicle?`${selectedVehicle.year} ${selectedVehicle.brand} ${selectedVehicle.model}`:(ar?'لا توجد سيارة محددة':'No vehicle selected')}</Text></View><Pill label={job?.status?.replaceAll('_',' ')||'READY'} icon="sparkles"/></View></Card>
  {messages.map(m=><View key={m.id} style={[s.msgRow,m.role==='user'&&{justifyContent:'flex-end'}]}>{m.role==='assistant'&&<View style={[s.bot,{backgroundColor:theme.primarySoft}]}><Ionicons name="sparkles" size={14} color={theme.primary}/></View>}<Glass intensity={m.role==='user'?28:48} style={[s.bubble,{maxWidth:'82%'},m.role==='user'?{backgroundColor:theme.primary,borderColor:'transparent'}:{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.msg,{color:m.role==='user'?'#fff':theme.ink,textAlign:ar?'right':'left'}]}>{m.text}</Text></Glass></View>)}
  {busy&&<View style={s.msgRow}><View style={[s.bot,{backgroundColor:theme.primarySoft}]}><Ionicons name="sparkles" size={14} color={theme.primary}/></View><Glass style={s.typing}><Text style={[s.typingText,{color:theme.muted}]}>●  ●  ●</Text></Glass></View>}
  <Text style={[s.disclaimer,{color:theme.muted2}]}>{ar?'Carma AI يقدم إرشادات عامة ولا يستبدل تشخيص الفني المعتمد.':'Carma AI provides general guidance and does not replace a qualified technician’s diagnosis.'}</Text>
 </ScrollView>
 <View style={s.bottom}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRow}>{quick.map(q=><Pressable key={q} onPress={()=>send(q)} style={[s.quick,{backgroundColor:theme.surfaceElevated,borderColor:theme.line}]}><Text style={[s.quickText,{color:theme.ink}]}>{q}</Text></Pressable>)}</ScrollView><Glass style={s.composer} intensity={65}><Pressable style={[s.plus,{backgroundColor:theme.primarySoft}]}><Ionicons name="add" size={20} color={theme.primary}/></Pressable><TextInput value={input} onChangeText={setInput} onSubmitEditing={()=>send()} placeholder={ar?'اسألي Carma AI...':'Ask Carma AI...'} placeholderTextColor={theme.muted2} style={[s.input,{color:theme.ink,textAlign:ar?'right':'left'}]} multiline/><Pressable onPress={()=>send()} style={[s.send,{backgroundColor:input.trim()?theme.primary:theme.lineStrong}]}><Ionicons name="arrow-up" size={18} color="#fff"/></Pressable></Glass></View>
 </KeyboardAvoidingView>
}
const s=StyleSheet.create({screen:{flex:1},header:{paddingTop:56,paddingHorizontal:16,paddingBottom:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},circle:{width:40,height:40,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},headBrand:{flexDirection:'row',alignItems:'center',gap:9},title:{fontSize:16,fontWeight:'900'},online:{flexDirection:'row',alignItems:'center',gap:5,marginTop:1},dot:{width:6,height:6,borderRadius:3},onlineText:{fontSize:8.5,fontWeight:'700'},chat:{padding:16,paddingBottom:190,gap:13},context:{padding:13,borderRadius:20},contextRow:{flexDirection:'row',alignItems:'center',gap:10},vehicleIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center'},contextLabel:{fontSize:7.5,fontWeight:'900',letterSpacing:.7},contextValue:{fontSize:11.5,fontWeight:'900',marginTop:3},msgRow:{flexDirection:'row',alignItems:'flex-end',gap:7},bot:{width:30,height:30,borderRadius:11,alignItems:'center',justifyContent:'center'},bubble:{borderRadius:20,paddingHorizontal:14,paddingVertical:11},msg:{fontSize:13,lineHeight:19,fontWeight:'600'},typing:{borderRadius:17,paddingHorizontal:14,paddingVertical:10},typingText:{fontSize:10,letterSpacing:2},disclaimer:{fontSize:8.5,lineHeight:13,textAlign:'center',paddingHorizontal:25,marginTop:4},bottom:{position:'absolute',left:0,right:0,bottom:0,paddingBottom:Platform.OS==='ios'?30:16},quickRow:{gap:7,paddingHorizontal:16,paddingBottom:9},quick:{borderWidth:1,borderRadius:99,paddingHorizontal:12,paddingVertical:8},quickText:{fontSize:9.5,fontWeight:'800'},composer:{marginHorizontal:12,borderRadius:24,padding:8,flexDirection:'row',alignItems:'flex-end',gap:8},plus:{width:36,height:36,borderRadius:13,alignItems:'center',justifyContent:'center'},input:{flex:1,minHeight:36,maxHeight:95,fontSize:13,paddingVertical:8},send:{width:36,height:36,borderRadius:13,alignItems:'center',justifyContent:'center'}}) as Record<string, any>
