import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { serviceCategories } from '@/data/catalog';
import { colors } from '@/theme';
export default function Parts(){const {language,selectedVehicle}=useApp();const ar=language==='ar';const [q,setQ]=useState('');const parts=useMemo(()=>serviceCategories.flatMap(c=>c.services.filter(s=>s.part).map(s=>({id:s.id,name:s.part!,service:ar?s.nameAr:s.name,price:s.partPrice||0,warranty:s.warranty||'Garage warranty',cat:ar?c.nameAr:c.name}))).filter(p=>`${p.name} ${p.service} ${p.cat}`.toLowerCase().includes(q.toLowerCase())),[q,ar]);return <ScrollView style={s.bg} contentContainerStyle={s.page}><View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={21}/></Pressable><View><Text style={s.title}>{ar?'قطع الغيار':'Parts catalog'}</Text><Text style={s.sub}>{selectedVehicle?.brand} {selectedVehicle?.model} · {ar?'أسعار استرشادية':'Indicative pricing'}</Text></View></View><View style={s.search}><Ionicons name="search" size={18} color={colors.muted}/><TextInput style={s.searchInput} value={q} onChangeText={setQ} placeholder={ar?'ابحثي عن قطعة':'Search battery, brakes, filter…'} placeholderTextColor={colors.muted2}/></View><View style={s.notice}><Ionicons name="information-circle" size={18} color={colors.blue}/><Text style={s.noticeText}>{ar?'يتم تأكيد توافق القطعة والسعر النهائي بواسطة الكراج باستخدام رقم الشاصي.':'Garage confirms exact fitment and final price against your VIN before approval.'}</Text></View>{parts.map((p,i)=><Card key={`${p.id}-${i}`} style={s.part}><View style={s.icon}><Ionicons name="cube" size={22} color={colors.primary}/></View><View style={{flex:1}}><View style={s.partTop}><Text style={s.partName}>{p.name}</Text><Pill label={p.cat.toUpperCase()} tone="blue"/></View><Text style={s.service}>{p.service}</Text><Text style={s.warranty}><Ionicons name="shield-checkmark-outline" size={11}/> {p.warranty}</Text></View><View style={s.price}><Text style={s.from}>{ar?'من':'FROM'}</Text><Text style={s.value}>AED {p.price}</Text></View></Card>)}<View style={{height:30}}/></ScrollView>}
const s=StyleSheet.create({bg:{backgroundColor:colors.canvas},page:{padding:18,paddingTop:58,paddingBottom:40,gap:13},head:{flexDirection:'row',alignItems:'center',gap:12},back:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},title:{fontSize:25,fontWeight:'900',color:colors.ink},sub:{fontSize:10.5,color:colors.muted,marginTop:3},search:{height:50,backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:colors.line,flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:14},searchInput:{flex:1,fontSize:12,color:colors.ink},notice:{backgroundColor:colors.blueSoft,borderRadius:15,padding:13,flexDirection:'row',gap:9},noticeText:{fontSize:9.5,color:colors.ink2,lineHeight:15,flex:1},part:{flexDirection:'row',alignItems:'center',gap:12,padding:14},icon:{width:47,height:47,borderRadius:15,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},partTop:{flexDirection:'row',alignItems:'center',gap:7},partName:{fontSize:12.5,fontWeight:'900',color:colors.ink,flexShrink:1},service:{fontSize:9.5,color:colors.muted,marginTop:4},warranty:{fontSize:8.5,color:colors.primary,marginTop:5,fontWeight:'700'},price:{alignItems:'flex-end'},from:{fontSize:7,color:colors.muted,fontWeight:'800'},value:{fontSize:12,fontWeight:'900',color:colors.ink,marginTop:2}}) as Record<string, any>
