import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors } from '@/theme';
export default function PaymentMethods(){const {language,methods,selectedPaymentId,selectPayment,payments}=useApp();const ar=language==='ar';return <ScrollView style={s.bg} contentContainerStyle={s.page}><View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={21}/></Pressable><View><Text style={s.title}>{ar?'طرق الدفع':'Payment methods'}</Text><Text style={s.sub}>{ar?'اختاري الطريقة الافتراضية':'Choose your default checkout method'}</Text></View></View>{methods.map(m=>{const on=m.id===selectedPaymentId;return <Pressable key={m.id} onPress={()=>selectPayment(m.id)}><Card style={[s.method,on&&s.on]}><View style={[s.icon,on&&s.iconOn]}><Ionicons name={m.icon as any} size={22} color={on?'#fff':colors.ink}/></View><View style={{flex:1}}><Text style={s.name}>{m.label}</Text><Text style={s.detail}>{m.detail}</Text></View>{on?<Pill label={ar?'افتراضي':'DEFAULT'} icon="checkmark-circle"/>:<Ionicons name="chevron-forward" size={17} color={colors.muted2}/>}</Card></Pressable>})}<View><Text style={s.section}>{ar?'آخر المدفوعات':'Recent payments'}</Text><Text style={s.sectionSub}>{ar?'سجل المعاملات التجريبية':'Demo transaction history'}</Text></View>{payments.length===0?<Card><Text style={s.empty}>{ar?'ما في مدفوعات لحد الآن.':'No payments yet.'}</Text></Card>:payments.map(p=><Card key={p.id} style={s.payment}><View style={s.paymentIcon}><Ionicons name="checkmark" size={18} color="#fff"/></View><View style={{flex:1}}><Text style={s.name}>{p.method}</Text><Text style={s.detail}>{p.reference} · {new Date(p.createdAt).toLocaleDateString()}</Text></View><Text style={s.amount}>AED {p.amount.toFixed(2)}</Text></Card>)}<View style={{height:30}}/></ScrollView>}
const s=StyleSheet.create({bg:{backgroundColor:colors.canvas},page:{padding:18,paddingTop:58,paddingBottom:40,gap:13},head:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:4},back:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},title:{fontSize:25,fontWeight:'900',color:colors.ink},sub:{fontSize:10.5,color:colors.muted,marginTop:3},method:{flexDirection:'row',alignItems:'center',gap:12,padding:14},on:{borderColor:colors.primary,borderWidth:1.5},icon:{width:45,height:45,borderRadius:14,backgroundColor:colors.canvas,alignItems:'center',justifyContent:'center'},iconOn:{backgroundColor:colors.primary},name:{fontSize:12.5,fontWeight:'900',color:colors.ink},detail:{fontSize:9.5,color:colors.muted,marginTop:3},section:{fontSize:17,fontWeight:'900',color:colors.ink,marginTop:8},sectionSub:{fontSize:10,color:colors.muted,marginTop:3},empty:{fontSize:11,color:colors.muted,textAlign:'center'},payment:{flexDirection:'row',alignItems:'center',gap:11,padding:14},paymentIcon:{width:37,height:37,borderRadius:13,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},amount:{fontSize:11.5,fontWeight:'900',color:colors.ink}}) as Record<string, any>
