import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors } from '@/theme';
export default function ServiceSummary(){const {language,selectedVehicle,selectedServices}=useApp();const ar=language==='ar';const subtotal=useMemo(()=>selectedServices.reduce((s,x)=>s+x.fromPrice,0),[selectedServices]);const vat=subtotal*.05;const total=subtotal+vat;return <ScrollView style={s.bg} contentContainerStyle={s.page}><View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={21}/></Pressable><View><Text style={s.title}>{ar?'مراجعة الطلب':'Review service'}</Text><Text style={s.sub}>{ar?'قبل إرسال الطلب للكراج':'Before sending to the garage'}</Text></View></View>
 <Card><View style={s.vehicle}><View style={s.carIcon}><Ionicons name="car-sport" size={24} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.vehicleName}>{selectedVehicle?.year} {selectedVehicle?.brand} {selectedVehicle?.model}</Text><Text style={s.meta}>{selectedVehicle?.plate} · {selectedVehicle?.mileage.toLocaleString()} km</Text></View><Pressable onPress={()=>router.push('/vehicles')}><Text style={s.change}>{ar?'تغيير':'Change'}</Text></Pressable></View></Card>
 <View><Text style={s.section}>{ar?'الخدمات المختارة':'Selected services'}</Text><Text style={s.desc}>{ar?'الكراج سيؤكد السعر النهائي بعد الفحص.':'The garage confirms final pricing after inspection.'}</Text></View>
 {selectedServices.map(x=><Card key={x.id} style={s.line}><View style={{flex:1}}><Text style={s.lineTitle}>{ar?x.nameAr:x.name}</Text><Text style={s.meta}>{x.duration}{x.part?` · ${x.part}`:''}</Text></View><Text style={s.linePrice}>AED {x.fromPrice.toLocaleString()}+</Text></Card>)}
 <Card><Pill label={ar?'تقدير مبدئي':'PRELIMINARY ESTIMATE'} tone="warning" icon="information-circle"/><Price label={ar?'الخدمات والقطع':'Services & parts'} value={subtotal}/><Price label={ar?'ضريبة القيمة المضافة 5%':'VAT 5%'} value={vat}/><View style={s.rule}/><View style={s.totalRow}><Text style={s.totalLabel}>{ar?'الإجمالي التقديري':'Estimated total'}</Text><Text style={s.total}>AED {total.toFixed(2)}</Text></View></Card>
 <View style={s.notice}><Ionicons name="shield-checkmark" size={20} color={colors.primary}/><Text style={s.noticeText}>{ar?'لن يبدأ أي إصلاح إضافي قبل موافقتج على السعر النهائي.':'No additional repair starts until you approve the final garage estimate.'}</Text></View>
 <Pressable style={s.pay} onPress={()=>router.push({pathname:'/payment/custom',params:{amount:total.toFixed(2)}})}><Text style={s.payText}>{ar?'المتابعة للدفع':'Continue to payment'}</Text><Ionicons name="arrow-forward" size={18} color="#fff"/></Pressable></ScrollView>}
function Price({label,value}:{label:string;value:number}){return <View style={s.priceRow}><Text style={s.priceLabel}>{label}</Text><Text style={s.priceValue}>AED {value.toFixed(2)}</Text></View>}
const s=StyleSheet.create({bg:{backgroundColor:colors.canvas},page:{padding:18,paddingTop:58,paddingBottom:40,gap:14},head:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:5},back:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},title:{fontSize:25,fontWeight:'900',color:colors.ink},sub:{fontSize:10.5,color:colors.muted,marginTop:3},vehicle:{flexDirection:'row',alignItems:'center',gap:12},carIcon:{width:45,height:45,borderRadius:14,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},vehicleName:{fontSize:14,fontWeight:'900',color:colors.ink},meta:{fontSize:9.5,color:colors.muted,marginTop:4},change:{fontSize:10,fontWeight:'900',color:colors.primary},section:{fontSize:18,fontWeight:'900',color:colors.ink},desc:{fontSize:10.5,color:colors.muted,marginTop:4},line:{flexDirection:'row',alignItems:'center',gap:12},lineTitle:{fontSize:12.5,fontWeight:'800',color:colors.ink},linePrice:{fontSize:12,fontWeight:'900',color:colors.ink},priceRow:{flexDirection:'row',justifyContent:'space-between',marginTop:14},priceLabel:{fontSize:11,color:colors.muted},priceValue:{fontSize:11,fontWeight:'800',color:colors.ink},rule:{height:1,backgroundColor:colors.line,marginVertical:15},totalRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},totalLabel:{fontSize:12,fontWeight:'900',color:colors.ink},total:{fontSize:20,fontWeight:'900',color:colors.primary},notice:{backgroundColor:colors.primarySoft,borderRadius:16,padding:14,flexDirection:'row',gap:10,alignItems:'center'},noticeText:{fontSize:10.5,color:colors.ink2,lineHeight:16,flex:1},pay:{backgroundColor:colors.primary,borderRadius:17,paddingVertical:15,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},payText:{fontSize:13,fontWeight:'900',color:'#fff'}}) as Record<string, any>
