import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors } from '@/theme';
export default function Vehicles(){const {language,vehicles,selectedVehicleId,selectVehicle}=useApp();const ar=language==='ar';return <ScrollView style={s.bg} contentContainerStyle={s.page}>
 <View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={21}/></Pressable><View style={{flex:1}}><Text style={s.title}>{ar?'سياراتي':'My Garage'}</Text><Text style={s.sub}>{ar?'اختاري السيارة للخدمة أو الونش':'Choose the vehicle for service or recovery'}</Text></View><Pressable style={s.add} onPress={()=>router.push('/vehicle-add')}><Ionicons name="add" size={22} color="#fff"/></Pressable></View>
 {vehicles.map(v=>{const on=v.id===selectedVehicleId;return <Pressable key={v.id} onPress={()=>selectVehicle(v.id)}><Card style={[s.car,on&&s.carOn]}><Image source={{uri:v.image}} style={s.image}/><View style={s.body}><View style={s.top}><View style={{flex:1}}><Text style={s.name}>{v.year} {v.brand} {v.model}</Text><Text style={s.trim}>{v.trim||v.fuel} · {v.color||v.transmission}</Text></View>{on&&<Pill label={ar?'محددة':'SELECTED'} tone="mint" icon="checkmark-circle"/>}</View><View style={s.stats}><Stat icon="speedometer-outline" text={`${v.mileage.toLocaleString()} km`}/><Stat icon="card-outline" text={v.plate}/><Stat icon="flash-outline" text={v.fuel}/></View></View></Card></Pressable>})}
 <Pressable style={s.addCard} onPress={()=>router.push('/vehicle-add')}><View style={s.addIcon}><Ionicons name="add" size={24} color={colors.primary}/></View><View><Text style={s.addTitle}>{ar?'إضافة سيارة':'Add another vehicle'}</Text><Text style={s.addSub}>{ar?'الماركة، الموديل، السنة واللوحة':'Brand, model, year and plate details'}</Text></View></Pressable><View style={{height:30}}/>
 </ScrollView>}
function Stat({icon,text}:{icon:any;text:string}){return <View style={s.stat}><Ionicons name={icon} size={13} color={colors.muted}/><Text style={s.statText}>{text}</Text></View>}
const s=StyleSheet.create({bg:{backgroundColor:colors.canvas},page:{padding:18,paddingTop:58,gap:15},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:4},back:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},title:{fontSize:25,fontWeight:'900',color:colors.ink},sub:{fontSize:10.5,color:colors.muted,marginTop:3},add:{width:43,height:43,borderRadius:14,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},car:{padding:0,overflow:'hidden'},carOn:{borderColor:colors.primary,borderWidth:1.5},image:{width:'100%',height:170,backgroundColor:'#E9EEEC'},body:{padding:16},top:{flexDirection:'row',gap:10,alignItems:'flex-start'},name:{fontSize:17,fontWeight:'900',color:colors.ink},trim:{fontSize:10.5,color:colors.muted,marginTop:4},stats:{flexDirection:'row',gap:7,flexWrap:'wrap',marginTop:14},stat:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.canvas,paddingHorizontal:9,paddingVertical:7,borderRadius:10},statText:{fontSize:9,fontWeight:'700',color:colors.ink2},addCard:{backgroundColor:colors.primarySoft,borderWidth:1,borderStyle:'dashed',borderColor:'#A6D8C5',borderRadius:22,padding:17,flexDirection:'row',alignItems:'center',gap:13},addIcon:{width:43,height:43,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},addTitle:{fontSize:13,fontWeight:'900',color:colors.ink},addSub:{fontSize:10,color:colors.muted,marginTop:3}}) as Record<string, any>
