import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { carBrands } from '@/data/catalog';
import { colors } from '@/theme';
import { Vehicle } from '@/types';
export default function AddVehicle(){const {language,addVehicle}=useApp();const ar=language==='ar';const [brandId,setBrandId]=useState('lexus');const brand=carBrands.find(b=>b.id===brandId)!;const [model,setModel]=useState(brand.models[0].name);const [year,setYear]=useState(2025);const [plate,setPlate]=useState('Dubai A ');const [mileage,setMileage]=useState('0');
 const chosen=useMemo(()=>brand.models.find(m=>m.name===model)||brand.models[0],[brand,model]);
 const pickBrand=(id:string)=>{const b=carBrands.find(x=>x.id===id)!;setBrandId(id);setModel(b.models[0].name);setYear(b.models[0].years[0])};
 const save=()=>{const v:Vehicle={id:`v-${Date.now()}`,brandId,brand:brand.name,model:chosen.name,year,plate:plate.trim()||'Dubai -',mileage:Number(mileage)||0,fuel:brandId==='tesla'?'Electric':'Petrol',transmission:'Automatic',image:chosen.image};addVehicle(v);router.replace('/vehicles')};
 return <ScrollView style={s.bg} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><View style={s.head}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={21}/></Pressable><View><Text style={s.title}>{ar?'إضافة سيارة':'Add vehicle'}</Text><Text style={s.sub}>{ar?'اختاري بيانات سيارتج':'Build your vehicle profile'}</Text></View></View>
 <Text style={s.label}>{ar?'الماركة':'Brand'}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.brands}>{carBrands.map(b=><Pressable key={b.id} style={[s.brand,brandId===b.id&&s.brandOn]} onPress={()=>pickBrand(b.id)}><View style={[s.brandDot,{backgroundColor:b.accent}]}/><Text style={[s.brandText,brandId===b.id&&{color:'#fff'}]}>{b.name}</Text></Pressable>)}</ScrollView>
 <Text style={s.label}>{ar?'الموديل':'Model'}</Text><View style={s.grid}>{brand.models.map(m=><Pressable key={m.name} style={[s.model,model===m.name&&s.modelOn]} onPress={()=>{setModel(m.name);setYear(m.years[0])}}><Image source={{uri:m.image}} style={s.modelImg}/><View style={s.modelBody}><Text style={s.modelName}>{m.name}</Text><Text style={s.modelBodyText}>{m.body}</Text></View>{model===m.name&&<View style={s.selected}><Ionicons name="checkmark" size={13} color="#fff"/></View>}</Pressable>)}</View>
 <Text style={s.label}>{ar?'السنة':'Year'}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.years}>{chosen.years.map(y=><Pressable key={y} style={[s.year,year===y&&s.yearOn]} onPress={()=>setYear(y)}><Text style={[s.yearText,year===y&&{color:'#fff'}]}>{y}</Text></Pressable>)}</ScrollView>
 <Card><Text style={s.inputLabel}>{ar?'رقم اللوحة':'Plate number'}</Text><TextInput value={plate} onChangeText={setPlate} style={s.input} placeholder="Dubai A 58291"/><Text style={[s.inputLabel,{marginTop:14}]}>{ar?'الممشى (كم)':'Mileage (km)'}</Text><TextInput value={mileage} onChangeText={setMileage} keyboardType="number-pad" style={s.input} placeholder="42180"/></Card>
 <Pressable style={s.save} onPress={save}><Text style={s.saveText}>{ar?'حفظ السيارة':'Save vehicle'}</Text><Ionicons name="checkmark-circle" size={19} color="#fff"/></Pressable></ScrollView>}
const s=StyleSheet.create({bg:{backgroundColor:colors.canvas},page:{padding:18,paddingTop:58,paddingBottom:40,gap:14},head:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},back:{width:42,height:42,borderRadius:14,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},title:{fontSize:25,fontWeight:'900',color:colors.ink},sub:{fontSize:10.5,color:colors.muted,marginTop:3},label:{fontSize:12,fontWeight:'900',color:colors.ink,marginTop:3},brands:{gap:8,paddingRight:18},brand:{paddingHorizontal:13,paddingVertical:10,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:colors.line,flexDirection:'row',gap:7,alignItems:'center'},brandOn:{backgroundColor:colors.charcoal,borderColor:colors.charcoal},brandDot:{width:8,height:8,borderRadius:4},brandText:{fontSize:10,fontWeight:'800',color:colors.ink},grid:{gap:10},model:{backgroundColor:'#fff',borderRadius:20,overflow:'hidden',borderWidth:1,borderColor:colors.line},modelOn:{borderColor:colors.primary,borderWidth:1.5},modelImg:{height:145,width:'100%',backgroundColor:'#E8EEEB'},modelBody:{padding:13},modelName:{fontSize:15,fontWeight:'900',color:colors.ink},modelBodyText:{fontSize:9.5,color:colors.muted,marginTop:3},selected:{position:'absolute',right:12,top:12,width:25,height:25,borderRadius:9,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},years:{gap:8},year:{paddingHorizontal:15,paddingVertical:10,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:colors.line},yearOn:{backgroundColor:colors.primary,borderColor:colors.primary},yearText:{fontSize:11,fontWeight:'800',color:colors.ink},inputLabel:{fontSize:10,fontWeight:'800',color:colors.muted},input:{marginTop:7,backgroundColor:colors.canvas,borderRadius:13,paddingHorizontal:13,paddingVertical:12,fontSize:13,color:colors.ink,borderWidth:1,borderColor:colors.line},save:{backgroundColor:colors.primary,borderRadius:17,paddingVertical:15,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},saveText:{color:'#fff',fontSize:13,fontWeight:'900'}}) as Record<string, any>
