import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors } from '@/theme';
function Price({label,value,bold=false}:{label:string;value:string;bold?:boolean}){return <View style={s.price}><Text style={[s.priceLabel,bold&&s.bold]}>{label}</Text><Text style={[s.priceValue,bold&&s.bold]}>{value}</Text></View>}
export default function Estimate(){const {job,language,updateStatus}=useApp();const ar=language==='ar';return <ScrollView contentContainerStyle={s.page}><View style={s.nav}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20}/></Pressable><Text style={s.navTitle}>{ar?'التشخيص وعرض السعر':'Diagnosis & estimate'}</Text><View style={{width:42}}/></View><Card><Pill label={ar?'تشخيص الفني':'TECHNICIAN DIAGNOSIS'} tone="blue"/><Text style={s.issue}>{ar?'ضعف في بطارية 12V، ونظام شحن الدينامو ضمن الحدود الطبيعية. يُنصح باستبدال البطارية.':'12V battery health is critically low. Alternator charging output is within specification. Battery replacement is recommended.'}</Text><View style={s.note}><Ionicons name="checkmark-circle" size={19} color={colors.primary}/><Text style={s.noteText}>{ar?'تم الفحص بجهاز تشخيص معتمد':'Verified diagnostic scan completed'}</Text></View></Card><Card><Text style={s.title}>{ar?'تفاصيل التكلفة':'Cost breakdown'}</Text><Price label={ar?'بطارية AGM أصلية':'OEM-spec AGM battery'} value="AED 780"/><Price label={ar?'أجرة تركيب وفحص':'Labour & diagnostics'} value="AED 420"/><Price label={ar?'رسوم الونش':'Recovery service'} value="AED 0"/><View style={s.line}/><Price label={ar?'المجموع قبل الضريبة':'Subtotal'} value="AED 1,200"/><Price label={ar?'ضريبة القيمة المضافة 5%':'VAT 5%'} value="AED 60"/><View style={s.line}/><Price label={ar?'الإجمالي':'Total'} value="AED 1,260" bold/></Card><View style={s.guarantee}><Ionicons name="shield-checkmark" size={22} color={colors.primary}/><Text style={s.guaranteeText}>{ar?'لن يبدأ أي إصلاح مدفوع قبل موافقتج.':'No paid repair starts before your approval.'}</Text></View><Pressable style={s.cta} onPress={()=>{updateStatus('approved');router.push(`/payment/${job.id}`)}}><Text style={s.ctaText}>{ar?'اعتماد عرض السعر · 1,260 درهم':'Approve estimate · AED 1,260'}</Text></Pressable><Pressable style={s.secondary}><Text style={s.secondaryText}>{ar?'التواصل مع الكراج':'Ask garage a question'}</Text></Pressable></ScrollView>}
const s=StyleSheet.create({page:{padding:20,paddingTop:54,paddingBottom:60,gap:16},nav:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:15,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},navTitle:{fontSize:16,fontWeight:'900',color:colors.ink},issue:{fontSize:15,fontWeight:'800',lineHeight:23,color:colors.ink,marginTop:15},note:{flexDirection:'row',gap:7,alignItems:'center',marginTop:14},noteText:{fontSize:11,color:colors.muted,fontWeight:'700'},title:{fontSize:18,fontWeight:'900',color:colors.ink,marginBottom:12},price:{flexDirection:'row',justifyContent:'space-between',paddingVertical:9},priceLabel:{fontSize:13,color:colors.muted},priceValue:{fontSize:13,fontWeight:'800',color:colors.ink},bold:{fontSize:17,fontWeight:'900',color:colors.ink},line:{height:1,backgroundColor:colors.line,marginVertical:5},guarantee:{flexDirection:'row',gap:10,alignItems:'center',backgroundColor:colors.mint,padding:15,borderRadius:17},guaranteeText:{fontSize:12,color:colors.ink,fontWeight:'800',flex:1},cta:{backgroundColor:colors.primary,borderRadius:18,padding:17,alignItems:'center'},ctaText:{color:'#fff',fontSize:15,fontWeight:'900'},secondary:{padding:13,alignItems:'center'},secondaryText:{color:colors.primary,fontWeight:'800'}}) as Record<string, any>
