import {Ionicons} from '@expo/vector-icons';
import {BlurView} from 'expo-blur';
import {LinearGradient} from 'expo-linear-gradient';
import React from 'react';
import {Platform,Pressable,StyleProp,StyleSheet,Text,View,ViewStyle} from 'react-native';
import {radius,useTheme} from '@/theme';

export function Glass({children,style,intensity=55}:{children:React.ReactNode;style?:StyleProp<ViewStyle>;intensity?:number}){
 const {scheme,theme}=useTheme();
 if(Platform.OS==='ios') return <BlurView intensity={intensity} tint={scheme==='dark'?'systemUltraThinMaterialDark':'systemUltraThinMaterialLight'} style={[s.glass,{borderColor:theme.glassBorder},style]}>{children}</BlurView>;
 return <View style={[s.glass,{backgroundColor:theme.surfaceElevated,borderColor:theme.glassBorder},style]}>{children}</View>
}
export function Card({children,style}:{children:React.ReactNode;style?:StyleProp<ViewStyle>}){const {theme}=useTheme();return <Glass style={[s.card,{shadowColor:theme.shadow},style]}>{children}</Glass>}
export function SectionTitle({title,action,onAction}:{title:string;action?:string;onAction?:()=>void}){const {theme}=useTheme();return <View style={s.sectionRow}><Text style={[s.section,{color:theme.ink}]}>{title}</Text>{action&&<Pressable onPress={onAction}><Text style={[s.action,{color:theme.primary}]}>{action}</Text></Pressable>}</View>}
export function Pill({label,tone='mint',icon}:{label:string;tone?:'mint'|'warning'|'blue'|'purple'|'danger'|'dark';icon?:any}){const {theme}=useTheme();const bg=tone==='warning'?theme.warningSoft:tone==='blue'?theme.blueSoft:tone==='purple'?theme.purpleSoft:tone==='danger'?theme.dangerSoft:tone==='dark'?'rgba(0,0,0,.28)':theme.primarySoft;const fg=tone==='warning'?theme.warning:tone==='blue'?theme.blue:tone==='purple'?theme.purple:tone==='danger'?theme.danger:tone==='dark'?'#fff':theme.primary;return <View style={[s.pill,{backgroundColor:bg,borderColor:theme.line}]}>{icon&&<Ionicons name={icon} size={12} color={fg}/>}<Text style={[s.pillText,{color:fg}]}>{label}</Text></View>}
export function QuickAction({icon,label,caption,onPress,tone='mint'}:{icon:any;label:string;caption?:string;onPress?:()=>void;tone?:'mint'|'blue'|'warning'|'purple'}){const {theme}=useTheme();const bg=tone==='blue'?theme.blueSoft:tone==='warning'?theme.warningSoft:tone==='purple'?theme.purpleSoft:theme.primarySoft;const fg=tone==='blue'?theme.blue:tone==='warning'?theme.warning:tone==='purple'?theme.purple:theme.primary;return <Pressable style={{flex:1}} onPress={onPress}><Card style={s.quick}><View style={[s.quickIcon,{backgroundColor:bg}]}><Ionicons name={icon} size={22} color={fg}/></View><Text numberOfLines={1} style={[s.quickLabel,{color:theme.ink}]}>{label}</Text>{caption&&<Text numberOfLines={1} style={[s.quickCaption,{color:theme.muted}]}>{caption}</Text>}</Card></Pressable>}
export function Metric({icon,label,value,caption,tone='mint'}:{icon:any;label:string;value:string;caption?:string;tone?:'mint'|'blue'|'warning'|'purple'}){const {theme}=useTheme();const bg=tone==='blue'?theme.blueSoft:tone==='warning'?theme.warningSoft:tone==='purple'?theme.purpleSoft:theme.primarySoft;const fg=tone==='blue'?theme.blue:tone==='warning'?theme.warning:tone==='purple'?theme.purple:theme.primary;return <Card style={s.metric}><View style={[s.metricIcon,{backgroundColor:bg}]}><Ionicons name={icon} size={18} color={fg}/></View><Text style={[s.metricLabel,{color:theme.muted}]}>{label}</Text><Text style={[s.metricValue,{color:theme.ink}]}>{value}</Text>{caption&&<Text style={[s.metricCaption,{color:theme.muted2}]}>{caption}</Text>}</Card>}
export function ProgressBar({value}:{value:number}){const {theme}=useTheme();return <View style={[s.progress,{backgroundColor:theme.line}]}><LinearGradient colors={[theme.primary,theme.blue]} style={[s.progressFill,{width:`${Math.max(0,Math.min(100,value))}%`}]} /></View>}
export function BrandMark({small=false}:{small?:boolean}){const {theme}=useTheme();return <LinearGradient colors={[theme.primary,theme.blue]} style={[s.brand,small&&s.brandSmall]}><Ionicons name="car-sport" size={small?17:21} color="#fff"/></LinearGradient>}
export function AmbientBackground(){const {theme,scheme}=useTheme();return <View pointerEvents="none" style={StyleSheet.absoluteFill}><View style={[s.orb,{backgroundColor:scheme==='dark'?'rgba(33,211,155,.12)':'rgba(41,193,150,.18)',top:-70,right:-80}]}/><View style={[s.orb,{backgroundColor:scheme==='dark'?'rgba(70,111,255,.11)':'rgba(78,126,255,.12)',bottom:80,left:-130,width:300,height:300,borderRadius:150}]}/><LinearGradient colors={[theme.canvas,'transparent',theme.canvas]} style={StyleSheet.absoluteFill}/></View>}
const s=StyleSheet.create({glass:{overflow:'hidden',borderWidth:1},card:{borderRadius:radius.lg,padding:18},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:2},section:{fontSize:19,fontWeight:'900',letterSpacing:-.3},action:{fontSize:12,fontWeight:'800'},pill:{alignSelf:'flex-start',paddingHorizontal:10,paddingVertical:6,borderRadius:radius.pill,flexDirection:'row',alignItems:'center',gap:5,borderWidth:1},pillText:{fontSize:10,fontWeight:'900',letterSpacing:.35},quick:{padding:13,borderRadius:21},quickIcon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',marginBottom:10},quickLabel:{fontSize:12,fontWeight:'900'},quickCaption:{fontSize:9.5,marginTop:3},metric:{flex:1,minWidth:0,padding:14,borderRadius:20},metricIcon:{width:34,height:34,borderRadius:12,alignItems:'center',justifyContent:'center'},metricLabel:{fontSize:10,fontWeight:'700',marginTop:11},metricValue:{fontSize:17,fontWeight:'900',marginTop:3},metricCaption:{fontSize:9.5,marginTop:3},progress:{height:7,borderRadius:99,overflow:'hidden'},progressFill:{height:'100%',borderRadius:99},brand:{width:42,height:42,borderRadius:15,alignItems:'center',justifyContent:'center'},brandSmall:{width:34,height:34,borderRadius:12},orb:{position:'absolute',width:260,height:260,borderRadius:130}}) as Record<string, any>
