import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Pill } from '@/components/UI';
import { StatusTimeline } from '@/components/StatusTimeline';
import { useApp } from '@/context/AppContext';
import { colors, radius } from '@/theme';
export default function JobDetail(){const {job,language}=useApp();const ar=language==='ar';return <ScrollView contentContainerStyle={s.page}><View style={s.nav}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20}/></Pressable><Text style={s.navTitle}>{job.id}</Text><Pressable style={s.back}><Ionicons name="call-outline" size={20} color={colors.primary}/></Pressable></View><Card><View style={s.row}><View><Pill label={job.status.replaceAll('_',' ').toUpperCase()} tone="warning"/><Text style={s.vehicle}>{job.vehicle}</Text><Text style={s.meta}>{job.plate} · {job.garage}</Text></View><View style={s.badge}><Ionicons name="construct" size={25} color={colors.primary}/></View></View></Card><Text style={s.section}>{ar?'تقدم الخدمة':'Service progress'}</Text><Card><StatusTimeline status={job.status} lang={language}/></Card><Text style={s.section}>{ar?'آخر تحديث':'Latest update'}</Text><Card><View style={s.row}><View style={s.updateIcon}><Ionicons name="search" size={21} color={colors.primary}/></View><View style={{flex:1,marginLeft:12}}><Text style={s.updateTitle}>{ar?'الفني يفحص نظام الشحن':'Technician is checking the charging system'}</Text><Text style={s.meta}>{job.updatedAt}</Text></View></View></Card>{['diagnosing','estimate_ready','approved','repairing','ready'].includes(job.status)&&<Pressable style={s.cta} onPress={()=>router.push(`/estimate/${job.id}`)}><Text style={s.ctaText}>{ar?'عرض التشخيص والتكلفة':'View diagnosis & estimate'}</Text><Ionicons name="arrow-forward" size={18} color="#fff"/></Pressable>}</ScrollView>}
const s=StyleSheet.create({page:{padding:20,paddingTop:54,paddingBottom:80,gap:16},nav:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:4},back:{width:42,height:42,borderRadius:15,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},navTitle:{fontSize:13,fontWeight:'900',color:colors.muted},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},vehicle:{fontSize:18,fontWeight:'900',color:colors.ink,marginTop:12},meta:{fontSize:11,color:colors.muted,marginTop:4},badge:{width:58,height:58,borderRadius:20,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center'},section:{fontSize:17,fontWeight:'900',color:colors.ink,marginTop:6},updateIcon:{width:48,height:48,borderRadius:16,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center'},updateTitle:{fontSize:13,fontWeight:'900',color:colors.ink},cta:{backgroundColor:colors.primary,borderRadius:radius.md,padding:17,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8,marginTop:6},ctaText:{color:'#fff',fontWeight:'900'}}) as Record<string, any>
